[package]
name = "rdl"
version = "0.1.0"
authors = ["Shaipe <Shaipe@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time= "0.2.23"

[lib]
name="rdl"
crate-type=["dylib"]
